### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by maartenpaauw**
Fix typo

### CODE REVIEW

**Comment by SpoturDeal** [comment]
Thanks, sometimes I type faster then I think.

**Comment by maartenpaauw** [comment]
No merge? 😄

**Comment by SpoturDeal** [comment]
Hoi Maarten,

I don't know how to merge give me some time to figure it out.

**Comment by SpoturDeal** [comment]
I think I did it. before I was on my phone, couldn't find it.

**Pull request merged**
